version: '3'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      FLASK_APP: app
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: redis
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web